### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by oxr463** [try0/mkdocs-toc-md#10]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/commands/build.py", line 354, in build
    config.plugins.on_post_build(config=config)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 542, in on_post_build
    return self.run_event('post_build', config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs/plugins.py", line 509, in run_event
    result = method(**kwargs)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_toc_md/plugin.py", line 137, in on_post_build
    self.output(config, self.nav, "", "")
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_toc_md/plugin.py", line 252, in output
    self.create_toc_items(toc_headers, nav_item, config, lang, nav_item_depth)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_toc_md/plugin.py", line 152, in create_toc_items
    self.create_toc_items(toc_items, child_item, config, lang, nav_item_depth)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_toc_md/plugin.py", line 152, in create_toc_items
    self.create_toc_items(toc_items, child_item, config, lang, nav_item_depth)
  File "/opt/homebrew/lib/python3.11/site-packages/mkdocs_toc_md/plugin.py", line 213, in create_toc_items
    toc_header.url = page.file.src_path + '#' + elm.get('id')
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by try0** [comment]
Thank you for reporting the issue.
Could you tell me the version of beautifulsourp and config(mkdocs.yml) you are using?

**Comment by oxr463** [comment]
```
pip3 list            
Package            Version
------------------ --------
astroid            3.0.1
beautifulsoup4     4.12.2
certifi            2023.5.7
cffi               1.16.0
charset-normalizer 3.2.0
click              8.1.7
dill               0.3.7
docutils           0.20.1
ghp-import         2.1.0
idna               3.4
isort              5.12.0
Jinja2             3.1.2
Markdown           3.5.1
markdown-it-py     3.0.0
MarkupSafe         2.1.3
mattermostdriver   7.3.2
mccabe             0.7.0
mdformat           0.7.17
mdurl              0.1.2
mergedeep          1.3.4
mkdocs             1.5.3
mkdocs-toc-md      0.0.8
packaging          23.2
pathspec           0.11.2
pip                23.3.1
platformdirs       3.11.0
pycparser          2.21
Pygments           2.16.1
pylint             3.0.2
python-dateutil    2.8.2
PyYAML             6.0.1
pyyaml_env_tag     0.1
requests           2.31.0
setuptools         68.1.2
six                1.16.0
soupsieve          2.5
tomlkit            0.12.2
typing_extensions  4.8.0
urllib3            2.0.3
watchdog           3.0.0
websockets         11.0.3
wheel              0.41.2
```

**Comment by try0** [comment]
I have checked that this plugin can get the id attribute in the same version as your environment. Maybe the output element has no id attribute.


I have changed that if the element does not have an id attribute, the plugin generates the URL without the hash property and outputs the log.
https://github.com/try0/mkdocs-toc-md/commit/e24f79ece97e9860cf4375abfd31896a8f5e36b0

Could you try v0.0.9?

**Comment by oxr463** [comment]
Looks good on my end. Thanks!
